## Tutorial 8 - Python Numpy

In [141]:
## import the library
import numpy as np 

In [145]:
lst = [1,2,3,4]
arr = np.array(lst)

In [147]:
type(arr)

numpy.ndarray

In [149]:
arr.shape

(4,)

In [155]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

arr1 = np.array([lst1, lst2, lst3])

In [157]:
arr1.shape

(3, 5)

In [159]:
arr


array([1, 2, 3, 4])

In [163]:
#indexing
arr[3]

4

In [165]:
arr[3] = 5


In [167]:
arr

array([1, 2, 3, 5])

In [169]:
arr[1:3]

array([2, 3])

In [171]:
arr[-1]


5

In [173]:
arr[:-1]

array([1, 2, 3])

In [175]:
arr[::]

array([1, 2, 3, 5])

In [177]:
arr[::-1]


array([5, 3, 2, 1])

In [181]:
arr[::-2]

array([5, 2])

In [183]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [185]:
arr1[:,1]

array([2, 3, 4])

In [187]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [189]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [191]:
##EDA
arr

array([1, 2, 3, 5])

In [195]:
arr[arr<2]

array([1])

In [197]:
arr1.shape


(3, 5)

In [199]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [215]:
## mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [217]:
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [219]:
arr*arr

array([ 1,  4,  9, 25])

In [221]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [223]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [225]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [233]:
np.random.randint(10,50,4).reshape(2,2)

array([[44, 35],
       [35, 26]])

In [235]:
np.random.random_sample((4,7))

array([[0.52979882, 0.80318744, 0.49431096, 0.47195132, 0.45823776,
        0.23723237, 0.49197108],
       [0.92288278, 0.74325797, 0.98730249, 0.9312608 , 0.67023231,
        0.16943554, 0.53886982],
       [0.42629275, 0.46837362, 0.52943255, 0.30885351, 0.68007212,
        0.51158889, 0.81342967],
       [0.56409083, 0.10072884, 0.89071552, 0.33878353, 0.56248145,
        0.04911162, 0.36773021]])